# Generated by Django 4.2.27 on 2025-12-10 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyalert',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_alerts_session', to='api.chatsession'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_trusted_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
